[gravity]
host = "0.0.0.0"
port = 32803
pingInterval = 10
maxPingsOutstanding = 3
maxReconnects = -1

[adapter]
adapter_id = "kafka_adapter"
adapter_name = "KAFKA Adapter"

[source]
config = "./settings/sources.json"
